### ISSUE TITLE
Crash on Cable through Unloaded Chunk

### ISSUE THREAD

**Issue by slidingmike** [MrRiegel/Storage-Network#80]
http://pastebin.com/2WYN7G5D

**Comment by KidsDontPlay** [comment]
I don't know why this happens.
@oitsjustjose , can you help me?
Is it actually necessary to check if the chunk is loaded?

**Comment by oitsjustjose** [comment]
[Here's the line that supposedly causes issues](https://github.com/oitsjustjose/Persistent-Bits/blob/master/src/main/java/com/oitsjustjose/persistent_bits/tileentity/TileChunkLoader.java#L82)

I have no idea why this is a problem, however. I'm pretty sure I'm doing everything alright, but I'll look into it some more and verify. You may also want to chat with @raoulvdberge and ask him how he fixed a somewhat similar problem with Refined Storage, because this isn't the first time I've heard PersistentBits cause issues with network based mods. Oddly, I"ve had no problems (even with large, multi-chunk setups) with mine on my server with EnderIO conduits, IC2 cables, RefinedStorage cables or even StorageDrawers Trim.

Let me know if I can help with anything - I'm honestly not super incredibly familiar with Forge Chunk Loading, so I may have to do a lot of research to find a fix if it's verified as a bug on my part.
